- name: Stop the stub listener
  when: ansible_facts['service_mgr'] == 'systemd'
  block:
    - name: Change the symbolic link
      ansible.builtin.file:
        state: link
        force: true
        src: ../run/systemd/resolve/resolv.conf
        path: /etc/resolv.conf

    - name: Edit resolved.conf
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNSStubListener='
        line: DNSStubListener=no

    - name: Restart resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted # reload unsupported
