---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create test containers
      loop: "{{ groups['all'] }}"
      loop_control:
        loop_var: _container_name
      community.docker.docker_container:
        name: "{{ _container_name }}"
        image: ubuntu:24.04 # renovate
        capabilities:
          - NET_ADMIN
        command: sleep inf
        default_host_ip: ''
        state: started
        devices:
          - /dev/net/tun
        published_ports:
          - "{{ hostvars[_container_name]['external_port'] }}:443"
        sysctls: # enable these parameters to be modified in the container
          net.ipv6.conf.all.disable_ipv6: 0
          net.ipv6.conf.all.forwarding: 1
