---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Test status
      ansible.builtin.include_tasks: tasks/test_stat.yml
      loop:
        - {path: "/tmp/download/instance0/client0.ovpn", mode: "0600"}
        - {path: "/tmp/download/instance0/client1.ovpn", mode: "0600"}
        - {path: "/tmp/download/instance1/client1.ovpn", mode: "0600"}
      vars:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
