- name: import install tasks
  ansible.builtin.import_tasks: install.yml

- name: import tls_crypt_v2 tasks
  ansible.builtin.import_tasks: tls_crypt_v2.yml

- name: import certificate tasks
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/certificate/main.yml"
  vars:
    subject_name: "{{ inventory_hostname }}"
    private_key_path: "{{ openvpn_server_key }}"
    certificate_path: "{{ openvpn_server_crt }}"
    fingerprint_path: "{{ openvpn_server_fingerprint }}"
