- name: check if UDP port 53 is in use
  ansible.builtin.shell:
    cmd: ss -nlu | tr '\t' ' ' | tr -s ' ' | cut -d ' ' -f 4 | grep ':53$'
  register: ss_udp_53_result
  ignore_errors: true
  changed_when: false

- name: stop the stub listener
  when: ss_udp_53_result is succeeded
  block:
    - name: ln
      ansible.builtin.file:
        state: link
        force: true
        src: ../run/systemd/resolve/resolv.conf
        path: /etc/resolv.conf

    - name: resolved.conf
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNSStubListener='
        line: DNSStubListener=no

    - name: restart resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted # reload unsupported
