---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Set container external ports
      loop: "{{ groups['ungrouped'] }}"
      loop_control:
        loop_var: _container_name
        index_var: _container_index
      ansible.builtin.set_fact:
        container_external_ports: >
          {{
            container_external_ports
            | default({})
            | ansible.builtin.combine({
                _container_name: 5300 + _container_index
              })
          }}

    - name: Install python3
      ansible.builtin.raw: >
        apt-get update &&
        apt-get install -y --no-install-recommends python3
      register: _wireguard_install_python3
      changed_when: "' 0 newly installed' not in _wireguard_install_python3.stdout"

    - name: Apply role under test
      ansible.builtin.include_role:
        name: wireguard
