- name: restart systemd openvpn
  ansible.builtin.systemd_service:
    name: openvpn-server@server
    state: restarted

- name: reload openvpn
  ansible.builtin.service:
    name: openvpn
    state: reloaded
