- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present
    update_cache: true

- name: Create nftables.conf
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: "/etc/nftables.conf"
    mode: u=rw,g=r,o=r

- name: Register current nft ruleset
  ansible.builtin.command:
    cmd: nft list ruleset
  register: _network_nft_list_ruleset_before
  changed_when: false

- name: Clear nft ruleset
  ansible.builtin.command:
    cmd: nft flush ruleset
  changed_when: false

- name: Load nft ruleset
  ansible.builtin.command:
    cmd: nft -f /etc/nftables.conf
  changed_when: false

- name: Detect nft ruleset change
  ansible.builtin.command:
    cmd: nft list ruleset
  register: _network_nft_list_ruleset_after
  changed_when: _network_nft_list_ruleset_before.stdout != _network_nft_list_ruleset_after.stdout

- name: Enable nftables service
  when: ansible_facts['service_mgr'] == 'systemd'
  ansible.builtin.service:
    name: nftables.service
    enabled: true
    state: started
