- name: 'register client fingerprints'
  ansible.builtin.shell:
    cmd: >
      /usr/bin/printf '/etc/openvpn/client/%s-fp.txt ' {{ clients | join(' ') }}
      | xargs cat
  register: fingerprints_result
  changed_when: false

- name: run server with systemd
  # https://community.openvpn.net/openvpn/wiki/Systemd
  when: ansible_facts.service_mgr == 'systemd'
  ansible.builtin.include_tasks: systemd.yml

- name: run server with sysvinit
  when: ansible_facts.service_mgr == 'sysvinit'
  ansible.builtin.include_tasks: sysvinit.yml
