- name: template server conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_server_dir }}/server.conf"
    mode: u=rw,g=r,o=r
  notify:
    - restart systemd openvpn

- name: start openvpn
  ansible.builtin.service:
    name: openvpn-server@server
    state: started
    enabled: true
