- name: template server conf
  ansible.builtin.template:
    src: "{{ conf_name }}.conf.j2"
    dest: "{{ openvpn_dir }}/{{ conf_name }}.conf"
    mode: u=rw,g=r,o=r
  notify:
    - reload openvpn

- name: start openvpn
  ansible.builtin.service:
    name: openvpn
    state: started
    enabled: true
