- name: Test line
  ansible.builtin.find:
    paths: "{{ path | dirname }}"
    patterns: "{{ path | basename }}"
    contains: "{{ line }}"
  register: _wireguard_find

- name: Assert match
  ansible.builtin.assert:
    that:
      - _wireguard_find.matched == matched
