name: deploy servers
on:
  push:
    branches:
      - main
    paths:
      - config.yml

jobs:
  terraform:
    uses: ./.github/workflows/apply.yml
    secrets:
      HCP_TERRAFORM_TEAM_TOKEN: ${{ secrets.HCP_TERRAFORM_TEAM_TOKEN }}

  ansible:
    needs: terraform
    if: fromJSON(needs.terraform.outputs.server-count) > 0
    uses: ./.github/workflows/ansible.yml
    with:
      terraform-output: "${{ needs.terraform.outputs.json-output }}"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
