name: integration tests
on:
  pull_request:

jobs:
  cue-deploy:
    if: ${{ endsWith(github.repository, '-dev') }}
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cue
        with:
          data-file: tests/config-it.yml
          schema-file: config.cue
  deploy:
    needs: cue-deploy
    uses: ./.github/workflows/deploy.yml
    with:
      config: tests/config-it.yml
      validate_tf: true
    secrets:
      HCP_TERRAFORM_TEAM_TOKEN: ${{ secrets.HCP_TERRAFORM_TEAM_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  test-deploy:
    needs: deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - name: server count is more than 0
        run: test "${{ needs.deploy.outputs.server-count }}" -gt 0

      - name: ansible succeeded
        run: test "${{ needs.deploy.outputs.ansible-result }}" = "success"

  cue-empty:
    needs: test-deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cue
        with:
          data-file: tests/config-empty.yml
          schema-file: config.cue

  empty:
    needs: cue-empty
    uses: ./.github/workflows/deploy.yml
    with:
      config: tests/config-empty.yml
      validate_tf: true
    secrets:
      HCP_TERRAFORM_TEAM_TOKEN: ${{ secrets.HCP_TERRAFORM_TEAM_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  test-empty:
    needs: empty
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - name: server count is 0
        run: test "${{ needs.empty.outputs.server-count }}" -eq 0

      - name: ansible skipped
        run: test "${{ needs.empty.outputs.ansible-result }}" = "skipped"
