name: integration tests
on:
  pull_request:

jobs:
  empty:
    if: ${{ endsWith(github.repository, '-dev') }}
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    defaults:
      run:
        working-directory: terraform
    env:
      SSH_USER: ubuntu
      CONFIG: tests/config-empty.yml
      PLAN_RESOURCES_JSON_PATH: /tmp/empty_plan_resources.json
      APPLY_OUTPUT_JSON_PATH: /tmp/empty_apply_output.json

    steps:
      - uses: actions/checkout@v6

      - run: >
          cat tests/config-empty.tpl.yml
          | sed "s/\${TERRAFORM_ORGANIZATION}/${ORGANIZATION}/"
          | sed "s/\${TERRAFORM_WORKSPACE}/${WORKSPACE}/"
          > tests/config-empty.yml
        env:
          ORGANIZATION: '${{ vars.TEST_TERRAFORM_ORGANIZATION }}'
          WORKSPACE: '${{ vars.TEST_TERRAFORM_WORKSPACE }}'

      - uses: ./.github/actions/cue
        with:
          data-file: terraform/tests/config-empty.yml
          schema-file: config.cue

      - name: set up terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ~1.14
          cli_config_credentials_token: ${{ secrets.HCP_TERRAFORM_TEAM_TOKEN }}
          terraform_wrapper: false # for `make`

      - run: >
          make -f commands.mk
          CONFIG="${CONFIG}"
          SSH_USER="${SSH_USER}"
          SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY}"
          init
        env:
          SSH_PUBLIC_KEY: '${{ vars.SSH_PUBLIC_KEY }}'

      - run: |
          terraform fmt -recursive -check
          terraform validate

      - run: >
          make -f commands.mk
          CONFIG="${CONFIG}"
          HCP_TERRAFORM_TEAM_TOKEN="${HCP_TERRAFORM_TEAM_TOKEN}"
          PLAN_RESOURCES_JSON_PATH="${PLAN_RESOURCES_JSON_PATH}"
          plan-resources
        env:
          HCP_TERRAFORM_TEAM_TOKEN: ${{ secrets.HCP_TERRAFORM_TEAM_TOKEN }}

      - run: |
          [ "$(cat ${{ env.PLAN_RESOURCES_JSON_PATH }})" = '[]' ]

      - run: >
          make -f commands.mk
          CONFIG="${CONFIG}"
          APPLY_OUTPUT_JSON_PATH=${APPLY_OUTPUT_JSON_PATH}
          apply-output

      - run: |
          [ "$(cat ${{ env.APPLY_OUTPUT_JSON_PATH }})" = '{}' ]
