name: prevent config commit
on:
  pull_request:
    paths:
      - '**/*config*.yml'
      - '**/*config*.yaml'
      - '!**/*example*'
      - '!ansible/**'
      - '!.github/**'
  push:
    paths:
      - '**/*config*.yml'
      - '**/*config*.yaml'
      - '!**/*example*'
      - '!ansible/**'
      - '!.github/**'

jobs:
  fail:
    if: github.repository_visibility != 'private'
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - run: false
