name: prevent config commit
on:
  pull_request:
    paths:
      - config.yml
  push:
    paths:
      - config.yml

jobs:
  fail:
    if: ${{ github.event.repository.is_template }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - run: false
