name: lint ansible files
on:
  pull_request:
    paths:
      - .github/workflows/unit-test-ansible-lint.yml
      - ansible/**/*.yml
      - ansible/**/*.yaml

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    defaults:
      run:
        working-directory: ansible

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - run: yamllint .

  ansible-lint:
    needs: yamllint
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ansible

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: install ansible-lint
        run: |
          python3 -m pip install ansible-lint
          ansible-galaxy collection install -r roles/network/requirements.yml
          ansible-galaxy collection install -r roles/wireguard/requirements.yml
          ansible-galaxy collection install -r roles/openvpn/molecule/default/collections.yml
          ansible-galaxy collection install -r roles/wireguard/molecule/default/collections.yml

      - run: ansible-lint
