name: unit tests
on:
  pull_request:
    paths:
      - .github/workflows/unit-tests.yml
      - .github/actions/cue/action.yml
      - config-example.yml
      - config.cue
      - terraform/modules/**/*.tf
      - terraform/policy/**/*.rego

jobs:
  cue:
    runs-on: ubuntu-24.04
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v6
      - name: validate example
        uses: ./.github/actions/cue
        with:
          data-file: config-example.yml
          schema-file: config.cue

  conftest:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    defaults:
      run:
        working-directory: terraform
    env:
      CONFTEST_VERSION: 0.67.0

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        id: cache
        with:
          path: ~/bin/conftest
          key: conftest-${{ env.CONFTEST_VERSION }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/bin
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz
          tar zxf conftest.tar.gz
          cp conftest ~/bin/conftest

      - run: echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

      - run: conftest fmt --check policy

      - run: conftest test -p policy/modules/aws -n main modules/aws/main.tf
      - run: conftest test -p policy/modules/aws -n outputs modules/aws/outputs.tf
      - run: conftest test -p policy/modules/aws -n variables modules/aws/variables.tf
      - run: conftest verify -p policy/modules/aws

      - run: conftest test -p policy/modules/google -n main modules/google/main.tf
      - run: conftest test -p policy/modules/google -n outputs modules/google/outputs.tf
      - run: conftest test -p policy/modules/google -n variables modules/google/variables.tf
      - run: conftest verify -p policy/modules/google
