name: validate terraform files
on:
  pull_request:
    paths:
      - .github/workflows/unit-test-hcl.yml
      - terraform/**/*.tf
      - terraform/**/*.rego

jobs:
  conftest:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    defaults:
      run:
        working-directory: terraform
    env:
      # renovate: datasource=github-releases depName=open-policy-agent/conftest
      CONFTEST_VERSION: 0.68.2

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: cache
        with:
          path: ~/bin/conftest
          key: conftest-${{ env.CONFTEST_VERSION }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/bin
          ARCH="$(uname -m | sed 's/aarch64/arm64/')"
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_${ARCH}.tar.gz
          tar zxf conftest.tar.gz
          cp conftest ~/bin/conftest

      - run: echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

      - run: conftest fmt --check policy

      - run: conftest test -p policy/modules/aws -n main modules/aws/main.tf
      - run: conftest test -p policy/modules/aws -n outputs modules/aws/outputs.tf
      - run: conftest test -p policy/modules/aws -n variables modules/aws/variables.tf
      - run: conftest verify -p policy/modules/aws

      - run: conftest test -p policy/modules/google -n main modules/google/main.tf
      - run: conftest test -p policy/modules/google -n outputs modules/google/outputs.tf
      - run: conftest test -p policy/modules/google -n variables modules/google/variables.tf
      - run: conftest verify -p policy/modules/google
