name: lint ansible files
on:
  pull_request:
    paths:
      - .github/workflows/unit-test-ansible-lint.yml
      - ansible/**/*.yml
      - ansible/**/*.yaml

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    defaults:
      run:
        working-directory: ansible

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - run: yamllint .

  ansible-lint:
    needs: yamllint
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    defaults:
      run:
        working-directory: ansible

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: install ansible-lint
        run: |
          python3 -m pip install ansible-lint
          ansible-galaxy collection install -r roles/openvpn/requirements.yml

      - run: ansible-lint
